export type Article = {
  slug: string;
  kind: "academy" | "media";
  title: string;
  excerpt: string;
  body: string[];
  category: string;
  artist: string;
  genre: string;
  author: string;
  image: string;
  date: string;
};

export const academyCategories = [
  "Music Marketing",
  "Spotify",
  "TikTok",
  "Instagram",
  "YouTube",
  "Radio",
  "DJs",
  "PR",
  "Artist Branding",
  "Release Strategy",
  "Music Business",
];

export const mediaCategories = [
  "News",
  "New Releases",
  "Interviews",
  "Reviews",
  "Music Videos",
  "Artist Features",
  "Industry News",
  "Events",
];

export const articles: Article[] = [
  {
    slug: "how-to-promote-your-new-song-in-nigeria",
    kind: "academy",
    title: "How to Promote Your New Song in Nigeria",
    excerpt: "A practical release week plan for artists who need radio, DJs, playlists, creators and press to work from the same brief.",
    category: "Music Marketing",
    artist: "",
    genre: "Afrobeats",
    author: "ClassicalPromo Academy",
    image: "/media/stage.jpg",
    date: "2026-08-12",
    body: [
      "A Nigerian release does not move because a song is online. It moves when the right people in specific cities have the record, the story and a reason to use it. Start with the audience you can actually describe: Lagos clubs, Abuja radio, Port Harcourt DJs, diaspora listeners in London, or a gospel community. A campaign that tries to be everywhere usually reports activity that does not belong to anyone.",
      "Prepare the public assets before you ask for attention. You need a clean master, artwork, a song link, a short biography, credits, and a press photo that looks like the project. If there is a video, say when it lands. If there is not, do not imply one. Curators, blogs and presenters lose time when the link is private or the title on the artwork does not match the file.",
      "Split the work by channel. Independent playlist curators need genre, mood and similar records. DJs need the clean version and a note about where it fits a night. Radio needs a servicing pack and a follow-up, not a mass email with twelve attachments. Creators need a point of view: a lyric, a dance, a city, a story. Press needs an angle that is not “new song out now”.",
      "Write down what you will count. Contacted, replied, posted, published and verified spins are campaign activity. Streams, followers and views can be observed later, but they are not something a promoter should promise in the proposal. If a number is missing, leave it blank. Invented dashboards make the next release harder to judge.",
      "Give the campaign a window. Two to four weeks is enough to service a single and learn which channels responded. At the end, keep the outlets that replied. The next release should start from that list, not from zero.",
    ],
  },
  {
    slug: "how-to-prepare-for-a-music-release",
    kind: "academy",
    title: "How to Prepare for a Music Release",
    excerpt: "The assets, dates and decisions that should be finished before a campaign starts.",
    category: "Release Strategy",
    artist: "",
    genre: "",
    author: "ClassicalPromo Academy",
    image: "/media/studio.jpg",
    date: "2026-07-28",
    body: [
      "Promotion cannot repair a release that is not ready. Before you pitch the song, lock the title, the artist name, featured credits and the release date. Changing the title after curators and stations have the file creates two records in the market and a messy report.",
      "Collect one folder: master, instrumental if you have it, artwork at a high resolution, lyrics, song link, video link, photos, logo and a biography of about 120 words. Name the files properly. “Final final 3” is not a press kit.",
      "Decide the markets before you buy ads or email DJs. A song aimed at Fuji radio in Ibadan is a different campaign from an Afrobeats record aimed at London playlists. Both can be right. They should not be hidden inside one vague goal called “worldwide exposure”.",
      "Set a budget you can finish. A smaller campaign that is fully serviced is more useful than a large plan that stops after the first week. Ask what the report will contain. If the answer is a guaranteed stream count, walk away.",
      "Tell your distributor, manager and any featured artists the same date. Campaign desks waste the first week chasing a link that is still private.",
    ],
  },
  {
    slug: "how-to-pitch-your-song-to-djs",
    kind: "academy",
    title: "How to Pitch Your Song to DJs",
    excerpt: "What DJs need in the first message, and what a servicing report should show afterwards.",
    category: "DJs",
    artist: "",
    genre: "Amapiano",
    author: "ClassicalPromo Academy",
    image: "/media/decks.jpg",
    date: "2026-07-02",
    body: [
      "DJs do not need your life story in the first message. They need the song, the tempo or a plain description of the groove, the city you are targeting, and a private link that works. If you want the record in Lagos, say so. If the vocal is in Yoruba, Pidgin or English, say that too. Context helps a selector decide faster.",
      "One song per pitch. A zip of an entire unreleased album is how your mail gets archived. Lead with the version you want played. Offer the instrumental only if it is useful for a mix.",
      "Follow up once. A second, short note is professional. A daily chase is not. Keep a list of who received the song, who replied, and who said they played it. “Sent to 2,000 DJs” is not a result if you cannot name the list.",
      "Do not pay anyone who promises a fixed number of club plays. Real DJs decline records. A useful campaign includes those declines, because they tell you whether the song, the city or the brief was wrong.",
      "After the campaign, keep the DJs who responded. They are the start of your own network, which is worth more than a one-off blast.",
    ],
  },
  {
    slug: "how-music-playlist-pitching-works",
    kind: "academy",
    title: "How Music Playlist Pitching Works",
    excerpt: "Independent curator outreach, what it can and cannot do, and why editorial playlists are a different door.",
    category: "Spotify",
    artist: "",
    genre: "",
    author: "ClassicalPromo Academy",
    image: "/media/headphones.jpg",
    date: "2026-06-18",
    body: [
      "There are two different conversations in playlist promotion, and they should never be mixed. Editorial playlists on a streaming service are programmed by that service. Independent playlists are programmed by curators. A promotion company can pitch curators. It cannot sell access to a service’s editorial team.",
      "A serious pitch is short. It names the song, the genre, the release date, two or three similar records, and the markets you care about. It includes a working link. It does not open with a demand to be added, and it does not offer payment for a fake stream target.",
      "Curators add records that fit the playlist they already run. If your song is mid-tempo R&B, a gym-amapiano playlist is the wrong desk even if that playlist is large. Relevance beats follower count.",
      "The report should show curators contacted, replies, and placements the curator confirms. A screenshot of a playlist with no curator relationship is not a placement you should brag about. Streams that arrive from a placement can be read in your distributor. They are an outcome, not a guarantee written into the invoice.",
      "Pitching is a relationship. Curators who trust your taste will open the next email. That only happens if you send them records that belong on their playlist.",
    ],
  },
  {
    slug: "how-to-build-a-tiktok-campaign-for-a-new-song",
    kind: "academy",
    title: "How to Build a TikTok Campaign for a New Song",
    excerpt: "Creator fit, sound choice and honest reporting for a release that needs short-form attention.",
    category: "TikTok",
    artist: "",
    genre: "Pop",
    author: "ClassicalPromo Academy",
    image: "/media/concert.jpg",
    date: "2026-05-30",
    body: [
      "A TikTok campaign is not a wish for a viral video. It is a decision about which part of the song a stranger can understand in a few seconds, and which creators already speak to that audience.",
      "Pick one hook. It might be a chorus line, a drum pattern, a dance that is simple enough to copy, or a scene from the video. Give creators the clean audio and permission to use it. Tell them what the song is about in two lines. Then let them make the post in their own voice. Scripts that sound like adverts travel badly.",
      "Separate organic creator outreach from paid ads. Both can be useful. They are different line items, different reports and different expectations. Ads can buy impressions. They cannot buy cultural uptake.",
      "Ask for a log: creators contacted, posts that actually published, and links. Add views and engagement only when the creator or the ad account provides them. Estimating a view count to make a report look finished is how artists lose trust.",
      "If the sound does not travel, say so. The next step might be a better hook, a different city of creators, or a decision that TikTok is not the lead channel for this record. That is a useful result.",
    ],
  },
  {
    slug: "music-promotion-strategies-for-independent-artists",
    kind: "academy",
    title: "Music Promotion Strategies for Independent Artists",
    excerpt: "How to choose a channel mix when you do not have a label team behind the release.",
    category: "Music Business",
    artist: "",
    genre: "",
    author: "ClassicalPromo Academy",
    image: "/media/session.jpg",
    date: "2026-05-09",
    body: [
      "Independent artists often try to copy a major-label week with none of the staff. The better approach is a smaller plan you can finish. Pick two or three channels that match the record. A club song needs DJs. A story song may need blogs, playlists and a patient video audience. A gospel record needs its own radio and community map.",
      "Own the assets. Your biography, photos, links and mailing list should live with you, not inside a promoter’s slide. A campaign is a rental of attention and labour. The audience relationship should come back to the artist.",
      "Spend in public categories: people who pitch, people who post, media who might cover you, and ads you can inspect. Do not spend on bundles of streams or followers. Those numbers do not book shows, and they put the release at risk.",
      "Use one dashboard. If playlist pitches, radio servicing and creator posts live in three chats, you cannot tell what happened. A campaign record with dates and a named owner is the minimum professional standard.",
      "Rebook only the channels that showed real activity. Loyalty to a tactic that produced no replies is not persistence. It is a habit.",
    ],
  },
  {
    slug: "how-to-build-a-music-press-kit",
    kind: "academy",
    title: "How to Build a Music Press Kit",
    excerpt: "The short set of materials a blogger, journalist or presenter needs before they can say yes.",
    category: "PR",
    artist: "",
    genre: "",
    author: "ClassicalPromo Academy",
    image: "/media/vinyl.jpg",
    date: "2026-04-16",
    body: [
      "A press kit is a favour to the person on the other side. It should answer the questions they will ask anyway, without making them hunt through your Instagram.",
      "Include a biography of about 120 words, a longer 300-word version, two or three photos with photographer credit, the latest release link, and a contact email that a manager actually reads. If you have previous coverage, link to it. If you do not, skip the section. Empty claims of “as seen in” damage the pitch.",
      "Photos should look like the current project. A picture from three years ago, shot in a different wardrobe, makes the story feel unfinished. You do not need a dozen images. You need two that print clearly.",
      "For a single, add credits: writers, producers, mix, master, label or “independent”. Presenters and editors use credits. They also notice when featured artists are missing.",
      "Keep the kit in one link or one PDF. Update it when the single changes. A campaign moves faster when the first email already contains everything required to publish.",
    ],
  },
  {
    slug: "sample-release-my-new-song",
    kind: "media",
    title: "Sample desk: what a new-release note should contain",
    excerpt: "A model release note for the fictional single My New Song, written to show the format ClassicalPromo Media will use.",
    category: "New Releases",
    artist: "Adaeze Okonkwo",
    genre: "Afrobeats",
    author: "ClassicalPromo Media",
    image: "/media/portrait.jpg",
    date: "2026-09-12",
    body: [
      "This is a sample editorial card, not a report of a commercial release. Adaeze Okonkwo is a fictional artist used to demonstrate ClassicalPromo profiles and campaigns.",
      "A real new-release note on this desk will name the song, the artists, the genre, the date, the cities the record is speaking to, and one concrete musical fact: a producer, a language, a featured player, a scene. It will link to the official audio. It will not invent chart positions.",
      "My New Song, in the sample campaign, is an Afrobeats single briefed for Lagos and the UK. The promotion attached to it is demonstration data, labelled as such inside the artist dashboard.",
      "When ClassicalPromo publishes actual release news, the artist will be real, the link will be official, and the copy will be dated. Until then, treat every profile marked sample as a layout, not a client list.",
    ],
  },
  {
    slug: "questions-for-a-first-interview",
    kind: "media",
    title: "Questions worth asking in a first interview",
    excerpt: "An interview format for emerging artists, using the sample profile only as a stand-in.",
    category: "Interviews",
    artist: "Adaeze Okonkwo",
    genre: "Afrobeats",
    author: "ClassicalPromo Media",
    image: "/media/mic.jpg",
    date: "2026-08-02",
    body: [
      "The first interview with an emerging artist should be specific. Where was the song made, who is in the room, which city is the chorus for, and what should a DJ understand before they play it? Those answers help listeners. A list of favourite celebrities does not.",
      "This page is a format sample. It is not an interview with a real artist, and Adaeze Okonkwo is not a ClassicalPromo client. We will not invent quotes.",
      "When a real interview is published here, you will see the artist’s own account of the record, a date, and a writer’s name. The artist will have approved the factual credits.",
      "Good interviews also mark what is not claimed. If the song is not on editorial playlists, the piece should not imply that it is. Promotion and journalism can share a building without sharing a script.",
    ],
  },
  {
    slug: "how-we-write-a-song-review",
    kind: "media",
    title: "How this desk writes a song review",
    excerpt: "What a ClassicalPromo review will cover, and the claims it will not make.",
    category: "Reviews",
    artist: "",
    genre: "R&B",
    author: "ClassicalPromo Media",
    image: "/media/session.jpg",
    date: "2026-06-22",
    body: [
      "A useful review describes the record: tempo, vocal approach, production choices, and who it might suit. It can be warm or critical. It should be specific enough that a reader who has not heard the song still learns something.",
      "It should not function as an advertisement with a star rating bolted on. If ClassicalPromo is also promoting the release, the review will say so. Readers can then judge the piece with that context.",
      "We will not review a song we have not heard, and we will not invent listener numbers to decorate a paragraph. Links to the official release are enough.",
      "Reviews live beside news, videos and features so artists have a media home that is held to the same standard as the campaign reports: clear, dated and sourced.",
    ],
  },
  {
    slug: "what-a-music-video-premiere-needs",
    kind: "media",
    title: "What a music video premiere actually needs",
    excerpt: "A checklist for artists sending a video to blogs, creators and audiences.",
    category: "Music Videos",
    artist: "",
    genre: "",
    author: "ClassicalPromo Media",
    image: "/media/festival.jpg",
    date: "2026-06-04",
    body: [
      "A premiere needs a public or scheduled link, a still image, credits for the director and the song, and a time zone. “Tonight” is not a time. Lagos, London and Toronto do not share one evening.",
      "Send the still in a size that a blog can crop. Send the director’s name in the first email. If the video uses a location or a dancer who should be credited, include that. Missing credits are the most common reason a post slips a day.",
      "Creators need a different cut from journalists. A vertical moment, cleared for reuse, will travel further than a request to “share the YouTube link”. Provide it if you have it. Do not pretend a lyric video is a location film.",
      "ClassicalPromo will post video features when there is a real link to embed. Sample cards on this site are labelled so they are not mistaken for coverage of a client.",
    ],
  },
  {
    slug: "reading-a-campaign-before-you-believe-it",
    kind: "media",
    title: "Industry note: read the activity, not the adjective",
    excerpt: "How to tell a promotion report from a promise, for managers and independent artists.",
    category: "Industry News",
    artist: "",
    genre: "",
    author: "ClassicalPromo Media",
    image: "/media/crowd.jpg",
    date: "2026-05-14",
    body: [
      "The music economy is full of screenshots. A serious report is duller and more useful. It says who was contacted, what was asked, what came back, and what is still unknown.",
      "Managers should ask three questions of any promoter. What will you do? What will you not promise? What will the artist receive in writing? If streams, followers or editorial playlists appear as deliverables, the proposal is selling an outcome the seller does not control, or worse, an outcome that will be faked.",
      "African artists are not a niche to be spoken down to. The same standard used for an international label brief should be used for a first single in Enugu or Kumasi: a scope, a price, a window and a report.",
      "This note is ClassicalPromo’s editorial position. It is not a news report about a named third-party company.",
    ],
  },
  {
    slug: "planning-a-listening-event",
    kind: "media",
    title: "Planning a listening event without inflating the room",
    excerpt: "A short guide for artists and labels hosting a playback, showcase or community session.",
    category: "Events",
    artist: "",
    genre: "",
    author: "ClassicalPromo Media",
    image: "/media/concert.jpg",
    date: "2026-04-28",
    body: [
      "A listening event works when the room is real. Invite DJs, presenters, editors and friends who might actually use the record. Publish a start time, a neighbourhood and a host. If the venue is not confirmed, do not announce the city as if the posters are printed.",
      "Capture the night with a photographer you have credited and a short recap. Attendance claims should match the room. A bar of forty people is a success if the right selector heard the chorus.",
      "Pair the event with the digital campaign instead of treating it as a separate story. The DJs in the room can be the same DJs on the servicing list. The photos can feed the press kit.",
      "ClassicalPromo’s events coverage will run when there is a date and a host we can name. Until a real calendar is live, this page explains the standard we will use.",
    ],
  },
  {
    slug: "artist-feature-format",
    kind: "media",
    title: "What an artist feature on ClassicalPromo includes",
    excerpt: "Biography, latest release, links and campaigns — without fake accolades.",
    category: "Artist Features",
    artist: "Adaeze Okonkwo",
    genre: "Afrobeats",
    author: "ClassicalPromo Media",
    image: "/media/singer.jpg",
    date: "2026-09-01",
    body: [
      "An artist feature is a public profile with a point of view. It carries the name, city, genre, a biography the artist stands behind, the latest release, and links the artist actually operates.",
      "The sample feature for Adaeze Okonkwo exists so labels and artists can see the layout: portrait, credits, campaign history and a verified badge that means ClassicalPromo has checked the profile. In the sample, the badge is demonstrative. On a live profile it will mean a real review.",
      "Features will not include purchased accolades, invented award lines, or logos of platforms presented as endorsements. If a playlist, station or paper covered the artist, the feature will link to that coverage.",
      "Artists who want a public profile can build it from the account area after a campaign, or ask the desk to review one. The profile stays theirs.",
    ],
  },
  {
    slug: "desk-note-on-sample-stories",
    kind: "media",
    title: "A note from the desk on sample stories",
    excerpt: "Why early ClassicalPromo Media pages are formats, and how real news will be marked.",
    category: "News",
    artist: "",
    genre: "",
    author: "ClassicalPromo Media",
    image: "/media/vinyl.jpg",
    date: "2026-09-20",
    body: [
      "ClassicalPromo is opening a media desk beside the promotion platform. The stories currently on the site are original explainers and clearly marked samples. They are not disguised client coverage and they are not aggregated celebrity news.",
      "Real news will name sources. A release note will link to the music. An event will name a date and a place. An interview will use approved quotes. If we do not have the fact, we will not write around it.",
      "Promotion clients are not automatically editorial subjects. When a campaign and a story overlap, the page will disclose that ClassicalPromo is working on the release.",
      "If you have a factual correction, write to hello@classicalpromo.com.ng. The desk would rather fix a line than defend a flourish.",
    ],
  },
];
